AppleShop.Web/Components/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace AppleShop.Web.Components;

public class FooterViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync()
    {
        return View();
    }
}

AppleShop.Web/Components/HeaderViewComponent.cs
using AppleShop.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace AppleShop.Web.Components;

public class HeaderViewComponent : ViewComponent
{
    private readonly ICategoryService _categoryService;

    public HeaderViewComponent(ICategoryService categoryService)
        => _categoryService = categoryService;

    public async Task<IViewComponentResult> InvokeAsync()
        => View(await _categoryService.GetAll());
}

AppleShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AppleShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <script src="https://cdn.jsdelivr.net/npm/@Html.Raw('@')popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
        integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@1c2407b26c61958baa93967b5412487cd94b290b/dist/aframe-master.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
    <script src="https://cdn.canvasjs.com/jquery.canvasjs.min.js"></script>
</head>
<body>
    <div>
        @await Component.InvokeAsync("Header")
        <main>
            @RenderBody()
        </main>
        @await Component.InvokeAsync("Footer")
    </div>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>