AppleShop.Web/Models/HomeViewModel.cs
namespace AppleShop.Web.Models;

public class HomeViewModel
{
    public DashboardViewModel Dashboard { get; }

    public HomeViewModel(Dictionary<string, int> amounts)
    {
        Dashboard = new DashboardViewModel(amounts);
    }
}

AppleShop.Web/Components/GetTopProductsViewComponent.cs
using AppleShop.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace AppleShop.Web.Components;

public class GetTopProductsViewComponent : ViewComponent
{
    private readonly IProductService _productService;

    public GetTopProductsViewComponent(IProductService productService)
        => _productService = productService;

    public async Task<IViewComponentResult> InvokeAsync()
    {
        return View(await _productService.GetTopProducts());
    }
}

AppleShop.Web/Controllers/HomeController.cs
using AppleShop.Web.Models;
using AppleShop.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace AppleShop.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductService _productService;
        private readonly IOptions<AppSettings> _settings;

        public HomeController(IProductService productService, IOptions<AppSettings> settings)
        {
            _productService = productService;
            _settings = settings;
        }

        public async Task<IActionResult> Index()
        {
            var dashboardAmount = await _productService.GetDashboardAmount();

            var result = new HomeViewModel(dashboardAmount);

            return View(result);
        }

        public async Task<IActionResult> Register()
        {
            return Redirect($"{_settings.Value.IdentityUrl}/Account/Register?returnUrl={_settings.Value.WebUrl}");
        }

        [Authorize]
        public async Task<IActionResult> Login()
        {
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Logout()
        {
            return SignOut("Cookies", "oidc");
        }
    }
}

AppleShop.Web/Controllers/ProductController.cs
using AppleShop.Web.Models;
using AppleShop.Web.Services;
using AppleShop.Web.Services.ModelRequests.Cart;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AppleShop.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICartService _cartService;

        public ProductController(IProductService productService, ICartService cartService)
        {
            _productService = productService;
            _cartService = cartService;
        }

        public async Task<IActionResult> Index(
            Guid? id,
            int? color = null,
            int? minPrice = null,
            int? maxPrice = null,
            int? memory = null,
            int pageNumber = 1,
            int pageSize = 10)
        {
            var products = await _productService.GetAll(id, color, minPrice, maxPrice, memory, pageNumber, pageSize);

            var result = new ProductListViewModel { Products = products };

            return View(result);
        }

        public async Task<IActionResult> Detail(Guid id)
        {
            var product = await _productService.GetById(id);

            var result = new ProductDetailViewModel { Product = product };

            return View(result);
        }

        [HttpPost]
        [ActionName("Detail")]
        [Authorize]
        public async Task<IActionResult> DetailPost(ProductDetailViewModel productDto)
        {
            CartDto cartDto = new()
            {
                CartHeader = new CartHeaderDto
                {
                    UserId = User.Claims.Where(u => u.Type == "sub")?.FirstOrDefault()?.Value
                }
            };

            var cartDetails = new CartDetailDto()
            {
                Count = productDto.Product.Count,
                ProductId = productDto.Product.Id
            };

            var productDetail = await _productService.GetById(productDto.Product.Id);

            if (productDetail != null)
            {
                cartDetails.Product = productDetail;
            }

            List<CartDetailDto> cartDetailsDtos = new();
            cartDetailsDtos.Add(cartDetails);
            cartDto.CartDetails = cartDetailsDtos;

            var accessToken = await HttpContext.GetTokenAsync("access_token");
            var addToCartResp = await _cartService.AddCartAsync(cartDto, accessToken);
            if (addToCartResp != null && addToCartResp.CartHeader?.CartHeaderId != null)
            {
                return RedirectToAction(nameof(Index), new { id = Guid.Empty });
            }

            return View(productDto);
        }

        public async Task<IActionResult> Real()
        {
            return View();
        }
    }
}

AppleShop.Web/Views/Home/Index.cshtml
@model AppleShop.Web.Models.HomeViewModel

<section class="hello p-0 m-0">
    <div class="container">
        <div class="row">
            <div class="d-flex align-items-center justify-content-center">
                <h1 class="text-white"><em>Hello</em> in <em>AppleShop</em></h1>
            </div>
        </div>
    </div>
</section>

<section class="hits p-0 m-0">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="hits-nav p-3">
                    <li class="nav-item">
                        <h4><a class="nav-link text-white" href="#">Топ продажу</a></h4>
                    </li>
                    <li class="nav-item">
                        <h4><a class="nav-link text-white" href="#">Новинки</a></h4>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

@await Component.InvokeAsync("GetTopProducts");

<section class="categories mt-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="category-banner-full">
                    <div class="banner-image">
                        <img src="~/images/macbook.png" alt="Macbook">
                    </div>
                    <div class="banner-container">
                        <div class="banner-title">
                            <a href="#">Mac</a>
                        </div>
                        <div class="banner-amount-of-products pt-3">
                            Товарів: @Model.Dashboard.MacAmount
                        </div>
                        <div class="pt-5">
                            <a asp-controller="Product" asp-action="Index" asp-route-id="@(Guid.Parse("D7E4B3A8-8652-4922-4ABE-08DB419A7FA2"))" class="banner-link">Переглянути моделі <i
                                    class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-7">
                <div class="category-banner-part">
                    <div class="banner-container">
                        <div class="banner-title">
                            <a href="#">iPhone</a>
                        </div>
                        <div class="banner-amount-of-products pt-3">
                            Товарів: @Model.Dashboard.IPhoneAmount
                        </div>
                        <div class="pt-5">
                            <a asp-controller="Product" asp-action="Index" asp-route-id="@(Guid.Parse("4A577D9F-32CF-453E-4ABB-08DB419A7FA2"))" class="banner-link">Переглянути моделі <i
                                    class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div>
                    <div class="banner-image">
                        <img src="~/images/iphone.png" alt="Macbook">
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="category-banner-part">
                    <div class="banner-container">
                        <div class="banner-title">
                            <a href="#">iPad</a>
                        </div>
                        <div class="banner-amount-of-products pt-3">
                            Товарів: @Model.Dashboard.IPadAmount
                        </div>
                        <div class="pt-5">
                            <a asp-controller="Product" asp-action="Index" asp-route-id="@(Guid.Parse("B422B561-7909-4D29-4ABD-08DB419A7FA2"))" class="banner-link">Переглянути моделі <i
                                    class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div>
                    <div class="banner-image">
                        <img src="~/images/ipad.png" alt="iPad">
                    </div>
                </div>
                <div class="category-banner-part mt-2">
                    <div class="banner-container">
                        <div class="banner-title">
                            <a href="#">Apple Watch</a>
                        </div>
                        <div class="banner-amount-of-products pt-3">
                            Товарів: @Model.Dashboard.AppleWatchAmount
                        </div>
                        <div class="pt-5">
                            <a asp-controller="Product" asp-action="Index" asp-route-id="@(Guid.Parse("B4C5DC85-1FA3-43A0-4ABC-08DB419A7FA2"))" class="banner-link">Переглянути моделі <i
                                    class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div>
                    <div class="banner-image">
                        <img src="~/images/applewatch.png" alt="iPad">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>